In [2]:
import pandas as pd
df = pd.read_csv("D:\\Superstore sales dataset.csv")

In [3]:
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,8/11/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,8/11/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,12/6/2016,16/6/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,11/10/2015,18/10/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,11/10/2015,18/10/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,21/1/2014,23/1/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,26/2/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,26/2/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,26/2/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,4/5/2017,9/5/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [6]:
df.shape

(9994, 21)

In [7]:
df.index

RangeIndex(start=0, stop=9994, step=1)

In [8]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='str')

In [10]:
df.min()

Row ID                                                           1
Order ID                                            CA-2014-100006
Order Date                                                1/1/2017
Ship Date                                                 1/1/2015
Ship Mode                                              First Class
Customer ID                                               AA-10315
Customer Name                                        Aaron Bergman
Segment                                                   Consumer
Country                                              United States
City                                                      Aberdeen
State                                                      Alabama
Postal Code                                                   1040
Region                                                     Central
Product ID                                         FUR-BO-10000112
Category                                                 Furniture
Sub-Category                                           Accessories
Product Name     "While you Were Out" Message Book, One Form pe...
Sales                                                        0.444
Quantity                                                         1
Discount                                                       0.0
Profit                                                   -6599.978
dtype: object

In [12]:
df.max()

Row ID                                         9994
Order ID                             US-2017-169551
Order Date                                 9/9/2017
Ship Date                                  9/9/2017
Ship Mode                            Standard Class
Customer ID                                ZD-21925
Customer Name                    Zuschuss Donatelli
Segment                                 Home Office
Country                               United States
City                                           Yuma
State                                       Wyoming
Postal Code                                   99301
Region                                         West
Product ID                          TEC-PH-10004977
Category                                 Technology
Sub-Category                                 Tables
Product Name     netTALK DUO VoIP Telephone Service
Sales                                      22638.48
Quantity                                         14
Discount                                        0.8
Profit                                     8399.976
dtype: object

In [13]:
df['Sales']

0       261.9600
1       731.9400
2        14.6200
3       957.5775
4        22.3680
          ...
9989     25.2480
9990     91.9600
9991    258.5760
9992     29.6000
9993    243.1600
Name: Sales, Length: 9994, dtype: float64

In [15]:
df.shape[0]

9994

In [16]:
df.shape[1]

21

In [17]:
df.select_dtypes(include=['float','int'])

      Row ID  Postal Code     Sales  Quantity  Discount    Profit
0          1        42420  261.9600         2      0.00   41.9136
1          2        42420  731.9400         3      0.00  219.5820
2          3        90036   14.6200         2      0.00    6.8714
3          4        33311  957.5775         5      0.45 -383.0310
4          5        33311   22.3680         2      0.20    2.5164
...      ...          ...       ...       ...       ...       ...
9989    9990        33180   25.2480         3      0.20    4.1028
9990    9991        92627   91.9600         2      0.00   15.6332
9991    9992        92627  258.5760         2      0.20   19.3932
9992    9993        92627   29.6000         4      0.00   13.3200
9993    9994        92683  243.1600         2      0.00   72.9480

[9994 rows x 6 columns]

In [18]:
df.select_dtypes(include=['float','int']).shape

(9994, 6)

In [ ]:
df[[]].mean()'Sales','Profit'

Sales     229.858001
Profit     28.656896
dtype: float64

In [6]:
df[['Sales','Profit']].median()

Sales     54.4900
Profit     8.6665
dtype: float64

In [7]:
df['Sales'].cumsum()                 # 11. Cumulative Sum

0       2.619600e+02
1       9.939000e+02
2       1.008520e+03
3       1.966098e+03
4       1.988466e+03
            ...
9989    2.296578e+06
9990    2.296670e+06
9991    2.296928e+06
9992    2.296958e+06
9993    2.297201e+06
Name: Sales, Length: 9994, dtype: float64

In [8]:
df['Sales'].cummax()                 # 12. Cumulative Max

0         261.9600
1         731.9400
2         731.9400
3         957.5775
4         957.5775
           ...
9989    22638.4800
9990    22638.4800
9991    22638.4800
9992    22638.4800
9993    22638.4800
Name: Sales, Length: 9994, dtype: float64

In [9]:
df['Sales'].cummin()                 # 13. Cumulative Min

0       261.960
1       261.960
2        14.620
3        14.620
4        14.620
         ...
9989      0.444
9990      0.444
9991      0.444
9992      0.444
9993      0.444
Name: Sales, Length: 9994, dtype: float64

In [10]:
df['Sales'].cumprod()                # 14. Cumulative Product

c:\Users\DELL\AppData\Local\Programs\Python\Python314\Lib\site-packages\numpy\_core\fromnumeric.py:54: RuntimeWarning: overflow encountered in accumulate
  return bound(*args, **kwds)

0       2.619600e+02
1       1.917390e+05
2       2.803224e+06
3       2.684304e+09
4       6.004252e+10
            ...
9989             inf
9990             inf
9991             inf
9992             inf
9993             inf
Name: Sales, Length: 9994, dtype: float64

In [11]:
# GroupBy examples (Bonus)
df.groupby('Category')['Sales'].sum()

Category
Furniture          741999.7953
Office Supplies    719047.0320
Technology         836154.0330
Name: Sales, dtype: float64

In [12]:
df.groupby('Region')['Profit'].mean()

Region
Central    17.092709
East       32.135808
South      28.857673
West       33.849032
Name: Profit, dtype: float64

In [20]:
df.dtypes

Row ID             int64
Order ID             str
Order Date           str
Ship Date            str
Ship Mode            str
Customer ID          str
Customer Name        str
Segment              str
Country              str
City                 str
State                str
Postal Code        int64
Region               str
Product ID           str
Category             str
Sub-Category         str
Product Name         str
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

In [21]:
df.select_dtypes(include=['float','int']).shape

(9994, 6)

In [23]:
df.select_dtypes(include=['object']).shape

C:\Users\DELL\AppData\Local\Temp\ipykernel_14948\2519217202.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include=['object']).shape

(9994, 15)

In [27]:
df['Customer Name'].str.lower()

0            claire gute
1            claire gute
2        darrin van huff
3         sean o'donnell
4         sean o'donnell
              ...
9989    tom boeckenhauer
9990         dave brooks
9991         dave brooks
9992         dave brooks
9993        chris cortes
Name: Customer Name, Length: 9994, dtype: str

In [28]:
df['Customer Name'].str.upper()

0            CLAIRE GUTE
1            CLAIRE GUTE
2        DARRIN VAN HUFF
3         SEAN O'DONNELL
4         SEAN O'DONNELL
              ...
9989    TOM BOECKENHAUER
9990         DAVE BROOKS
9991         DAVE BROOKS
9992         DAVE BROOKS
9993        CHRIS CORTES
Name: Customer Name, Length: 9994, dtype: str

In [29]:
df["City"].str.upper()

0             HENDERSON
1             HENDERSON
2           LOS ANGELES
3       FORT LAUDERDALE
4       FORT LAUDERDALE
             ...
9989              MIAMI
9990         COSTA MESA
9991         COSTA MESA
9992         COSTA MESA
9993        WESTMINSTER
Name: City, Length: 9994, dtype: str

In [31]:
df['City'].str.lower()

0             henderson
1             henderson
2           los angeles
3       fort lauderdale
4       fort lauderdale
             ...
9989              miami
9990         costa mesa
9991         costa mesa
9992         costa mesa
9993        westminster
Name: City, Length: 9994, dtype: str

In [32]:
df['City'].str.len()

0        9
1        9
2       11
3       15
4       15
        ..
9989     5
9990    10
9991    10
9992    10
9993    11
Name: City, Length: 9994, dtype: int64

In [34]:
df['Customer Name'].str.strip()

0            Claire Gute
1            Claire Gute
2        Darrin Van Huff
3         Sean O'Donnell
4         Sean O'Donnell
              ...
9989    Tom Boeckenhauer
9990         Dave Brooks
9991         Dave Brooks
9992         Dave Brooks
9993        Chris Cortes
Name: Customer Name, Length: 9994, dtype: str

In [35]:
df['Customer Name'].str.replace("Claire Gute","swarna")

0                 swarna
1                 swarna
2        Darrin Van Huff
3         Sean O'Donnell
4         Sean O'Donnell
              ...
9989    Tom Boeckenhauer
9990         Dave Brooks
9991         Dave Brooks
9992         Dave Brooks
9993        Chris Cortes
Name: Customer Name, Length: 9994, dtype: str

In [36]:
df[df['Product Name'].str.contains("Chair")]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
1,2,CA-2016-152156,8/11/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.940,3,0.0,219.5820
23,24,US-2017-156909,16/7/2017,18/7/2017,Second Class,SF-20065,Sandra Flanagan,Consumer,United States,Philadelphia,...,19140,East,FUR-CH-10002774,Furniture,Chairs,"Global Deluxe Stacking Chair, Gray",71.372,2,0.3,-1.0196
39,40,CA-2015-117415,27/12/2015,31/12/2015,Standard Class,SN-20710,Steve Nguyen,Home Office,United States,Houston,...,77041,Central,FUR-CH-10004218,Furniture,Chairs,"Global Fabric Manager's Chair, Dark Gray",212.058,3,0.3,-15.1470
52,53,CA-2015-115742,18/4/2015,22/4/2015,Standard Class,DP-13000,Darren Powers,Consumer,United States,New Albany,...,47150,Central,FUR-CH-10003061,Furniture,Chairs,"Global Leather Task Chair, Black",89.990,1,0.0,17.0981
57,58,CA-2016-111682,17/6/2016,18/6/2016,First Class,TB-21055,Ted Butterfield,Consumer,United States,Troy,...,12180,East,FUR-CH-10003968,Furniture,Chairs,Novimex Turbo Task Chair,319.410,5,0.1,7.0980
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9908,9909,US-2015-129007,13/9/2015,15/9/2015,First Class,KD-16615,Ken Dana,Corporate,United States,Anaheim,...,92804,West,FUR-FU-10002379,Furniture,Furnishings,Eldon Econocleat Chair Mats for Low Pile Carpets,207.350,5,0.0,24.8820
9912,9913,CA-2015-132388,10/10/2015,12/10/2015,First Class,KN-16390,Katherine Nockton,Corporate,United States,Santa Barbara,...,93101,West,FUR-CH-10001714,Furniture,Chairs,"Global Leather & Oak Executive Chair, Burgundy",362.136,3,0.2,-54.3204
9919,9920,CA-2016-149272,15/3/2016,19/3/2016,Standard Class,MY-18295,Muhammed Yedwab,Corporate,United States,Bryan,...,77803,Central,FUR-CH-10000863,Furniture,Chairs,Novimex Swivel Fabric Task Chair,528.430,5,0.3,-143.4310
9947,9948,CA-2017-121559,1/6/2017,3/6/2017,Second Class,HW-14935,Helen Wasserman,Corporate,United States,Indianapolis,...,46203,Central,FUR-CH-10003746,Furniture,Chairs,Hon 4070 Series Pagoda Round Back Stacking Chairs,1925.880,6,0.0,539.2464
9990,9991,CA-2017-121258,26/2/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.960,2,0.0,15.6332

In [37]:
df[df['Customer Name'].str.startswith("A")]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
12,13,CA-2017-114412,15/4/2017,20/4/2017,Standard Class,AA-10480,Andrew Allen,Consumer,United States,Concord,...,28027,South,OFF-PA-10002365,Office Supplies,Paper,Xerox 1967,15.552,3,0.2,5.4432
17,18,CA-2014-167164,13/5/2014,15/5/2014,Second Class,AG-10270,Alejandro Grove,Consumer,United States,West Jordan,...,84084,West,OFF-ST-10000107,Office Supplies,Storage,Fellowes Super Stor/Drawer,55.500,2,0.0,9.9900
124,125,US-2014-152030,26/12/2014,28/12/2014,Second Class,AD-10180,Alan Dominguez,Home Office,United States,Houston,...,77041,Central,FUR-CH-10004063,Furniture,Chairs,Global Deluxe High-Back Manager's Chair,600.558,3,0.3,-8.5794
187,188,CA-2016-157000,16/7/2016,22/7/2016,Standard Class,AM-10360,Alice McCarthy,Corporate,United States,Grand Prairie,...,75051,Central,OFF-ST-10001328,Office Supplies,Storage,"Personal Filing Tote with Lid, Black/Gray",37.224,3,0.2,3.7224
188,189,CA-2016-157000,16/7/2016,22/7/2016,Standard Class,AM-10360,Alice McCarthy,Corporate,United States,Grand Prairie,...,75051,Central,OFF-PA-10001950,Office Supplies,Paper,Southworth 25% Cotton Antique Laid Paper & Env...,20.016,3,0.2,6.2550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9975,9976,US-2016-103674,6/12/2016,10/12/2016,Standard Class,AP-10720,Anne Pryor,Home Office,United States,Los Angeles,...,90032,West,OFF-PA-10000743,Office Supplies,Paper,Xerox 1977,13.360,2,0.0,6.4128
9976,9977,US-2016-103674,6/12/2016,10/12/2016,Standard Class,AP-10720,Anne Pryor,Home Office,United States,Los Angeles,...,90032,West,TEC-PH-10002496,Technology,Phones,Cisco SPA301,249.584,2,0.2,31.1980
9977,9978,US-2016-103674,6/12/2016,10/12/2016,Standard Class,AP-10720,Anne Pryor,Home Office,United States,Los Angeles,...,90032,West,OFF-FA-10003467,Office Supplies,Fasteners,"Alliance Big Bands Rubber Bands, 12/Pack",13.860,7,0.0,0.0000
9978,9979,US-2016-103674,6/12/2016,10/12/2016,Standard Class,AP-10720,Anne Pryor,Home Office,United States,Los Angeles,...,90032,West,OFF-BI-10003727,Office Supplies,Binders,Avery Durable Slant Ring Binders With Label Ho...,13.376,4,0.2,4.6816
9979,9980,US-2016-103674,6/12/2016,10/12/2016,Standard Class,AP-10720,Anne Pryor,Home Office,United States,Los Angeles,...,90032,West,OFF-BI-10002026,Office Supplies,Binders,Ibico Recycled Linen-Style Covers,437.472,14,0.2,153.1152

In [38]:
df[df['Customer Name'].str.endswith("n")]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
5,6,CA-2014-115812,9/6/2014,14/6/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.860,7,0.0,14.1694
6,7,CA-2014-115812,9/6/2014,14/6/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.280,4,0.0,1.9656
7,8,CA-2014-115812,9/6/2014,14/6/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.152,6,0.2,90.7152
8,9,CA-2014-115812,9/6/2014,14/6/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-BI-10003910,Office Supplies,Binders,DXL Angle-View Binders with Locking Rings by S...,18.504,3,0.2,5.7825
9,10,CA-2014-115812,9/6/2014,14/6/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AP-10002892,Office Supplies,Appliances,Belkin F5C206VTEL 6 Outlet Surge,114.900,5,0.0,34.4700
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9957,9958,US-2014-143287,11/11/2014,17/11/2014,Standard Class,KN-16705,Kristina Nunn,Home Office,United States,New Rochelle,...,10801,East,OFF-PA-10004039,Office Supplies,Paper,Xerox 1882,223.920,4,0.0,109.7208
9958,9959,US-2014-143287,11/11/2014,17/11/2014,Standard Class,KN-16705,Kristina Nunn,Home Office,United States,New Rochelle,...,10801,East,OFF-SU-10001574,Office Supplies,Supplies,Acme Value Line Scissors,7.300,2,0.0,2.1900
9980,9981,US-2015-151435,6/9/2015,9/9/2015,Second Class,SW-20455,Shaun Weien,Consumer,United States,Lafayette,...,70506,South,FUR-TA-10001039,Furniture,Tables,KI Adjustable-Height Table,85.980,1,0.0,22.3548
9987,9988,CA-2017-163629,17/11/2017,21/11/2017,Standard Class,RA-19885,Ruben Ausman,Corporate,United States,Athens,...,30605,South,TEC-AC-10001539,Technology,Accessories,Logitech G430 Surround Sound Gaming Headset wi...,79.990,1,0.0,28.7964
9988,9989,CA-2017-163629,17/11/2017,21/11/2017,Standard Class,RA-19885,Ruben Ausman,Corporate,United States,Athens,...,30605,South,TEC-PH-10004006,Technology,Phones,Panasonic KX - TS880B Telephone,206.100,5,0.0,55.6470

In [40]:
df['First Name'] = df['Customer Name'].str.split().str[0]
df['First Name']

0       Claire
1       Claire
2       Darrin
3         Sean
4         Sean
         ...
9989       Tom
9990      Dave
9991      Dave
9992      Dave
9993     Chris
Name: First Name, Length: 9994, dtype: object

In [56]:
df['Order Number'] = df['Order ID'].str.extract('(\d+)')  
df['Order Number']

<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
C:\Users\DELL\AppData\Local\Temp\ipykernel_14948\2825446302.py:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
  df['Order Number'] = df['Order ID'].str.extract('(\d+)')

0       2016
1       2016
2       2016
3       2015
4       2015
        ...
9989    2014
9990    2017
9991    2017
9992    2017
9993    2017
Name: Order Number, Length: 9994, dtype: str

#### MATHEMATICAL FUNCTIONS

In [44]:
df['Sales'].sum()

np.float64(2297200.8603)

In [45]:
df['Sales'].min()

np.float64(0.444)

In [46]:
df['Sales'].max()

np.float64(22638.48)

In [48]:
df['Sales'].median()

np.float64(54.489999999999995)

In [49]:
df['Sales'].mean()

np.float64(229.85800083049827)

In [50]:
df['Sales'].mode()

0    12.96
Name: Sales, dtype: float64

In [51]:
df['Sales'].std()                    # 8. Standard Deviation

np.float64(623.2451005086808)

In [52]:
df['Sales'].var()

np.float64(388434.45530807565)

In [53]:
df['Profit'].abs()                   #  Absolute

0        41.9136
1       219.5820
2         6.8714
3       383.0310
4         2.5164
          ...
9989      4.1028
9990     15.6332
9991     19.3932
9992     13.3200
9993     72.9480
Name: Profit, Length: 9994, dtype: float64

In [ ]:
df['Sales'].round(2)                 #  Round

0       261.96
1       731.94
2        14.62
3       957.58
4        22.37
         ...
9989     25.25
9990     91.96
9991    258.58
9992     29.60
9993    243.16
Name: Sales, Length: 9994, dtype: float64

In [55]:
df['Sales'] ** 2                     #  Power

0        68623.041600
1       535736.163600
2          213.744400
3       916954.668506
4          500.327424
            ...
9989       637.461504
9990      8456.641600
9991     66861.547776
9992       876.160000
9993     59126.785600
Name: Sales, Length: 9994, dtype: float64

In [ ]:
df['Profit'].abs()                   #  Absolute

0        41.9136
1       219.5820
2         6.8714
3       383.0310
4         2.5164
          ...
9989      4.1028
9990     15.6332
9991     19.3932
9992     13.3200
9993     72.9480
Name: Profit, Length: 9994, dtype: float64

In [58]:
df['Sales'].round(2)                 # 16. Round

0       261.96
1       731.94
2        14.62
3       957.58
4        22.37
         ...
9989     25.25
9990     91.96
9991    258.58
9992     29.60
9993    243.16
Name: Sales, Length: 9994, dtype: float64

In [ ]:
df['Sales'] ** 2                     #  Power

0        68623.041600
1       535736.163600
2          213.744400
3       916954.668506
4          500.327424
            ...
9989       637.461504
9990      8456.641600
9991     66861.547776
9992       876.160000
9993     59126.785600
Name: Sales, Length: 9994, dtype: float64

In [61]:
df['Sales'].corr(df['Profit'])       # 19. Correlation

np.float64(0.4790643497377061)

In [63]:
df['Profit_Margin'] = (df['Profit'] / df['Sales']) * 100  
df['Profit_Margin']

0       16.00
1       30.00
2       47.00
3      -40.00
4       11.25
        ...
9989    16.25
9990    17.00
9991     7.50
9992    45.00
9993    30.00
Name: Profit_Margin, Length: 9994, dtype: float64

In [74]:
df.columns

Index(['s', 'v'], dtype='str')

In [79]:
import pandas as pd
import numpy as np
data = {
    'Month': ['Jan','Feb','Mar','Apr','May','Jun'],
    'Sales': [1000, 1500, 1200, 1800, 2000, 1700],
    'Profit': [200, 300, 250, 400, 500, 350],
    'Expenses': [800, 1200, 950, 1400, 1500, 1350]
}

In [80]:
df = pd.DataFrame(data)
df.set_index('Month', inplace=True)

In [85]:
df

       Sales  Profit  Expenses
Month
Jan     1000     200       800
Feb     1500     300      1200
Mar     1200     250       950
Apr     1800     400      1400
May     2000     500      1500
Jun     1700     350      1350